# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-VMonitor
version:      2.06
version_from: lib/Apache/VMonitor.pm
installdirs:  site
requires:
    Apache::Scoreboard:            2.08
    Apache::Test:                  1.15
    GTop:                          0.12
    mod_perl2:                     2.0
    Template:                      2.0
    Time::HiRes:                   1.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
